receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp:
    endpoint: "${DT_ENDPOINT}/api/v2/otlp"
    headers:
      Authorization: "Api-Token ${DT_API_TOKEN}"

  debug/detailed:
    verbosity: detailed

processors:
  filter:
    error_mode: ignore
    metrics:
      metric:
        - 'IsMatch(metric.name, "coffeeshop.*") == false'

service:
  pipelines:
    metrics/debug:
      receivers: [otlp]
      processors: [filter]
      exporters: [debug/detailed]
