receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp:
    endpoint: "${DT_ENDPOINT}/api/v2/otlp"
    headers:
      Authorization: "Api-Token ${DT_API_TOKEN}"

  debug/detailed:
    verbosity: detailed

  debug/basic:
    verbosity: basic

processors:
  filter:
    error_mode: ignore
    metrics:
      metric:
        - 'IsMatch(metric.name, "coffeeshop.*") == false'

  transform:
    error_mode: ignore
    metric_statements:
      - delete_key(resource.attributes, "process.command_args")
      - replace_pattern(datapoint.attributes["customer_email"], "[^@]+(@.+)", "redacted$$1")
      - set(metric.description, "The number of beverages ordered") where metric.name == "coffeeshop.beverages_ordered"

service:
  pipelines:
    metrics/debug:
      receivers: [otlp]
      processors: [filter, transform]
      exporters: [debug/detailed]

    metrics/ingest:
      receivers: [otlp]
      processors: [transform]
      exporters: [otlphttp, debug/basic]
