receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp:
    endpoint: "${DT_ENDPOINT}/api/v2/otlp"
    headers:
      Authorization: "Api-Token ${DT_API_TOKEN}"

  debug/detailed:
    verbosity: detailed

service:
  pipelines:
    metrics/debug:
      receivers: [otlp]
      processors: []
      exporters: [debug/detailed]
